### ISSUE TITLE
hi~ 您好，我有个关于radare2的问题，想请教下！谢谢

### ISSUE THREAD

**Issue by 420313439** [BurningTeng/wintools#1]
我在r2的仓库中看到了你的一个issue，https://github.com/radareorg/radare2/issues/16943

在Visual Panel Mode（v）中，当遇到scanf等从键盘的标准输入的时候，总会多一个'~'出来，或者干脆就不给我输入，直接跳过了。我也遇到了同样的问题，请问您有什么解决办法吗？谢谢！

**Comment by BurningTeng** [comment]
Hi ,
你好，我在公众号写了一篇文章。你可以参考下。







破解工具Radare2

https://mp.weixin.qq.com/s?__biz=MzI1NjEyMzgxMw==&amp;mid=2247483720&amp;idx=1&amp;sn=f95ef690ead08dfed6abd6eb9000d25f&amp;chksm=ea2a3782dd5dbe94a6444a3f586cde0eca42b376990c089a29ca663be2e07796175b2b280548&amp;token=1415334185&amp;lang=zh_CN#rd



Thanks,
BurningTeng


------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Peiwen ***@***.***&gt;;
Send time:&nbsp;Saturday, Oct 30, 2021 10:40 PM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;[BurningTeng/wintools] hi~ 您好，我有个关于radare2的问题，想请教下！谢谢 (Issue #1)





 
我在r2的仓库中看到了你的一个issue，radareorg/radare2#16943
 
在Visual Panel Mode（v）中，当遇到scanf等从键盘的标准输入的时候，总会多一个'~'出来，或者干脆就不给我输入，直接跳过了。我也遇到了同样的问题，请问您有什么解决办法吗？谢谢！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 420313439** [comment]
我想我最近摸索出了一个解决办法，在scanf、gets的下一条汇编语句设置断点，然后按F9运行（而不是F8），这样就可以避免在输入时产生~字符
